version: '3'

services:
  books_php:
    image: "laravel-dev:${IMG_VERSION}"
    volumes:
      - ./application:/srv/www
    depends_on:
      - database

  nginx:
    image: "nginx-dev:${IMG_VERSION}"
    environment:
      FAST_CGI_HOST: books_php
      FAST_CGI_PORT: 9000
      LISTEN_PORT: 8080
      SERVER_NAME: books.local
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    ports:
      - 80:8080
    volumes:
      - ./application:/srv/www
    depends_on:
      - books_php

  database:
    image: "mysql-dev:${IMG_VERSION}"
    environment:
      MYSQL_DATABASE: db_app
      MYSQL_USER: books
      MYSQL_PASSWORD: books
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - 3306:3306
    volumes:
      - ./db_data:/var/lib/mysql

  database_test:
    image: "mysql-dev:${IMG_VERSION}"
    environment:
      MYSQL_DATABASE: db_test
      MYSQL_USER: books
      MYSQL_PASSWORD: books
      MYSQL_ROOT_PASSWORD: toor
    ports:
      - 3307:3306
